version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_very_complex_password
    volumes:
      - mysql-data:/var/lib/mysql
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_PASSWORD: my_very_complex_password
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./plugins/:/var/www/html/wp-content/plugins/
      - ./themes/:/var/www/html/wp-content/themes/
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - 8082:80